server:
  port: 9098                                # 项目访问端口，默认 8080
  servlet:                                 # 项目访问路径，默认 /
    context-path: /ShopOnline-rpc
# Spring
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ShopOnline?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1           #初始连接数
      max-active: 20            #最大连接数
      max-idle: 20              #最大空闲
      min-idle: 1               #最小空闲
      max-wait: 60000           #最大等待时间
  redis:
    timeout: 10000ms                        # 连接超时时间
    host: localhost                         # Redis服务器地址
    port: 6379                              # Redis服务器端口
    database: 0                             # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024                    # 最大连接数，默认 8
        max-wait: 10000ms                   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200                       # 最大空闲连接，默认 8
        min-idle: 5                         # 最小空闲连接，默认 0
  # Dubbo
  dubbo:
    #开启dubbo服务
    server: true
    # 提供方应用信息，用于计算依赖关系
    application:
      name: rpc-provider
      # 使用 zookeeper 注册中心暴露服务地址
    registry:
      address: zookeeper://127.0.0.1:2181
    # 用 dubbo 协议在 20880 端口暴露服务
    protocol:
      name: dubbo
      port: 20880
      # 扫描需要暴露的服务接口包
      scan:
      base-packages: com.cuit.service
# MyBatis
mybatis:
  # 配置 MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.cuit.rpc.entity
  # 配置 MyBatis Mapper 映射文件
  mapper-locations: classpath:mapper/*.xml
  # Mybatis SQL 打印(方法接口所在的包，不是 Mapper.xml 所在的包)
logging:
  level:
    com.cuit.managerment.mapper: debug
# Redis Key
# 商品分类列表 Key
goods.category.list.key: goods:category:list:goodsCategoryList